//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflectra.KronoDesk.Service.Email.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inflectra.KronoDesk.Service.Email.UI.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, any email message that is linked to an existing Ticket or Artifact where the user does not have permissions to view or add comments, the message will be attached as an attachment..
        /// </summary>
        public static string Detail_Email_Attach3rdParty_Help {
            get {
                return ResourceManager.GetString("Detail_Email_Attach3rdParty_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the entire email message will be attached to the Ticket or Artifact as an attachment..
        /// </summary>
        public static string Detail_Email_AttachMessage_Help {
            get {
                return ResourceManager.GetString("Detail_Email_AttachMessage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an exception while trying to connect to the server:.
        /// </summary>
        public static string Details_App_ErrorTesting_Msg {
            get {
                return ResourceManager.GetString("Details_App_ErrorTesting_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting!.
        /// </summary>
        public static string Details_App_ErrorTesting_Title {
            get {
                return ResourceManager.GetString("Details_App_ErrorTesting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, the email subject and body will be scanned for any matching product names. The first match will determine which product or project the email gets imported into. Otherwise, it will be imported into the default project/product..
        /// </summary>
        public static string Details_Email_RegexContent_Help {
            get {
                return ResourceManager.GetString("Details_Email_RegexContent_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, messages will be deleted from the server after downloading..
        /// </summary>
        public static string Details_Email_RemoveMessages_Help {
            get {
                return ResourceManager.GetString("Details_Email_RemoveMessages_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Fields.
        /// </summary>
        public static string Details_Email_Required_Title {
            get {
                return ResourceManager.GetString("Details_Email_Required_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address field is required..
        /// </summary>
        public static string Details_Email_RequiredAddress_Msg {
            get {
                return ResourceManager.GetString("Details_Email_RequiredAddress_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an application server and default project/product for importing..
        /// </summary>
        public static string Details_Email_RequiredProject_Msg {
            get {
                return ResourceManager.GetString("Details_Email_RequiredProject_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server&apos;s URL is required..
        /// </summary>
        public static string Details_Email_RequiredServer_Msg {
            get {
                return ResourceManager.GetString("Details_Email_RequiredServer_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this application server? All email accounts that use this server will become disabled..
        /// </summary>
        public static string Main_DeleteApp_AreYouSure_Msg {
            get {
                return ResourceManager.GetString("Main_DeleteApp_AreYouSure_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Server?.
        /// </summary>
        public static string Main_DeleteApp_AreYouSure_Title {
            get {
                return ResourceManager.GetString("Main_DeleteApp_AreYouSure_Title", resourceCulture);
            }
        }
    }
}
